#+STARTUP: fold indent
#+OPTIONS: tex:t toc:2 H:6 ^:{}

#+TITLE: Configuring Windows 11 for Research Computing
#+AUTHOR: Derek Devnich

* Overview
This repository contains documentation and test scripts for the KL 336 workstations.

** Location
1. The canonical version lives here: https://github.com/devnich/windows-setup
2. Each workstation should have its own copy here: *Documents/Installers/windows-setup*

** Manifest
1. Testing scripts are in *windows-setup/scripts*
2. Testing data are in *windows-setup/data*

* Post-upgrade QA
** Pre-test updates
1. Open the pinned GitBash app.
2. Navigate to *Documents/Installers/windows-setup*
   #+begin_src bash
   cd Documents/installers/windows-setup/
   #+end_src
3. Run
   #+begin_src bash
   git pull
   #+end_src

** Python (command line)
1. Open the pinned Terminal app. This should open Windows PowerShell.
2. Navigate to *Documents/Installers/windows-setup/scripts*
   #+begin_src bash
   cd .\Documents\Installers\windows-setup\scripts\
   #+end_src
3. Run
   #+begin_src bash
   python labtest.py
   #+end_src

*** Success criteria
1. Script runs without errors
2. Terminal prints "Completed Python script test"

** Python (Jupyter Lab)
1. In same terminal, run
   #+begin_src bash
   jupyter lab
   #+end_src
   Jupyter Lab should open in the browser
2. Open "labtest_python.ipynb"
3. In the *Kernel* menu, select "Restart Kernel and Run All Cells"

*** Success criteria
1. Script runs without errors
2. After last notebook cell, Jupyter Lab prints "Completed Python notebook test"

** Julia (Jupyter Lab)
1. In currently-running Jupyter Lab, open "labtest_julia.ipynb"
2. In the *Kernel* menu, select "Restart Kernel and Run All Cells"

*** Success criteria
1. Script runs without errors
2. Terminal prints "Completed Julia notebook test"

** Julia (command line)
1. Close all Jupyter Lab tabs without saving changes
2. Shut down Jupyter Lab
3. In same terminal, run
   #+begin_src bash
   julia labtest.jl
   #+end_src

*** Success criteria
1. Script runs without errors
2. Terminal prints "Completed Julia script test"

** R (RStudio)
1. Open the pinned RStudio app
2. Navigate to *Documents/Installers/windows-setup/scripts*
3. Open "labtest.R"
4. Click "Source" button to run script

*** Success criteria
1. Script runs without errors
2. R Console prints "Completed R script test"

** SQL
1. Open pinned DBBrowser for SQLite app
2. Click "Open Database". Navigate to *Documents/Installers/windows-setup/data* and select "portal_mammals.sqlite".
3. Click "Execute SQL"
4. In the toolbar, click "Open SQL file(s)". Navigate to *Documents/Installers/windows-setup/scripts* and select "labtest.sql".
5. In the toolbar, click "Execute all"

*** Success criteria
1. Script runs without errors
2. The "summer_2000" view is properly created. To verify:
   1. Click "Database Structure"
   2. In the toolbar, click "Refresh"
   3. "summer_2000" appears in the Views section

** COMMENT Github via GitBash
No easy way to automate the testing of Git and GitBash. Best approach is probably to pick a random computing and go through the repository push/pull sequence with Github

** Post-test cleanup
1. Remove Github credentials
   1. Open Credential Manager
   2. Select "Windows Credentials"
   3. If a Github credential exists, remove it
2. Reset repository to default state
   1. Open the pinned GitBash app.
   2. Navigate to *Documents/Installers/windows-setup*
      #+begin_src bash
      cd Documents/installers/windows-setup/
      #+end_src
   3. Run
      #+begin_src bash
      git restore .
      #+end_src
3. Shut down all terminals

* Application configuration
** General installation instructions
1. Make sure you are logged in as the DatVisLabWest user. Installing as the LibITLabWest user will break some applications.
2. You can find all of the installers in *Documents/Installers*. When installing:
   - Add the program to the Start Menu
   - Don't create a Desktop shortcut
   - Don't add the program to the Taskbar
3. Some applications require changing the default installation parameters. Check the "Application-specific installation instructions" section to see if you need to make any changes.
4. If an application automatically opens after installation, check the "Application-specific configuration instructions" section to see if you need to make any changes.
5. Don't perform any auto-updates during installation.

** COMMENT Update obsolete versions (summer 2025)
The following applications were installed using obsolete installers (from 2023). They should be completely un-installed and re-installed:
1. Anaconda Python
2. Git for Windows
3. R
4. RStudio
5. DB Browser for SQLite
6. MobaXTerm

** Application manifest
Where to find the most recent version of every application.

1. (Deprecated) Anaconda Python distribution: https://www.anaconda.com/download/success
   - Installer located under Distribution Installers → Windows → 64-Bit Graphical Installer
2. Miniforge Python installer: https://conda-forge.org/download/
3. Chrome: https://www.google.com/chrome/
4. DB Browser for SQLite: https://sqlitebrowser.org/dl/
   - Choose the Standard installer for 64-bit Windows
5. DejaVu fonts: https://dejavu-fonts.github.io
6. Firefox: https://www.mozilla.org/en-US/firefox/all/desktop-release/win64-msi/en-US/
7. Git for Windows: https://github.com/git-for-windows/git/releases/latest
   - Installer located under Assets → Git-/version-number/-64-bit.exe
8. Julia: https://apps.microsoft.com/store/detail/9NJNWW8PVKMN
9. Microsoft Office: https://it.ucmerced.edu/software-list
10. Microsoft Powertoys: https://apps.microsoft.com/store/detail/microsoft-powertoys/XP89DCGQ3K6VLD
    - There is no local installer
11. MobaXTerm: https://mobaxterm.mobatek.net/download-home-edition.html
    - Choose the Installer edition
12. Notepad++: https://notepad-plus-plus.org/downloads/
13. R: https://cran.r-project.org/bin/windows/base/
14. RStudio: https://posit.co/download/rstudio-desktop/
15. (On hold) uv: https://docs.astral.sh/uv/getting-started/installation/
    - There is no local installer

** Application-specific installation instructions
*** Anaconda Python distribution
1. Uninstall previous version
2. Delete Start Menu items for previous version.
   - Navigate to *DataVisLabWest/AppData/Roaming/Microsoft/Windows/Start Menu/Programs*
   - Delete the "Anaconda" folder
3. Install for single user ("Just Me" option)
4. Select "Create shortcuts" (this should be checked by default)
5. When setup in complete, de-select "Launch Anaconda Navigator" and "Welcome to Anaconda" and click "Finish"
6. Open Anaconda PowerShell Prompt and run the following command:

   #+BEGIN_SRC bash
   conda create -n lab --clone base
   #+END_SRC

7. When the process is complete (it will take several minutes), you may close PowerShell

*** Miniforge Python
1. Install info:
   - Carpentry install instructions: https://www.tim-dennis.com/2026-05-11-uc-lc/
   - Complete install instructions: https://github.com/conda-forge/miniforge
   - PowerShell permissions: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies
2. Do not add Miniforge to the PATH
3. By default, conda is only available from the Miniforge Prompt. To make it available from other terminals (including PowerShell), open Miniforge Prompt and run:
   #+begin_src bash
   conda init
   #+end_src

   This will create (or update) the profile.ps1 file in DataVisLabWest/Documents/WindowsPowerShell/
4. By default, the lab computers will not allow execution of PowerShell scripts, including the profile contained in profile.ps1 . To allow local script execution, open PowerShell and run:
   #+begin_src bash
   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
   #+end_src

   Conda should be available when you restart PowerShell.
5. Clone https://github.com/devnich/windows-setup to DataVisLabWest/Documents/Installers/
6. Create a new environment for Carpentry workshops
   #+begin_src bash
   conda env create -f .\Documents\Installers\windows-setup\config\carpentries_environment.yml
   #+end_src
7. Configure Conda to auto-activate the carpentry environment
   #+begin_src bash
   conda config --set default_activation_env carpentry
   conda config --set auto_activate True
   #+end_src

   Note that the configuration changes only work in PowerShell. The Miniforge Prompt will continue to start with the (base) environment.

*** DB Browser for SQLite
1. De-select the the option to create a Program Menu entry for "DB Browser (SQLCipher)".

*** DejaVu Fonts
1. Open Settings → Personalization → Fonts
2. Open *Documents/Installers/dejavu-fonts-ttf-<version>/ttf*. Select all of the font files and drag them into the "Drag and drop to install" pane in Settings.

*** Git for Windows
1. Run the installer. Click *Next* four times (two times if you've previously installed Git). You don't need to change anything in the Information, Location, Components, or Start Menu screens.
2. For each configuration screen, select the appropriate option and click *Next*:
   1. Choosing the default editor used by git: select *Use the Nano editor by default* from the dropdown menu (you will need to scroll up to find it)
   2. Adjusting the name of the initial branch in new repositories: select *Let Git decide*
   3. Adjusting your PATH environment: select *Git from the command line and also from 3rd-party software* (if you don't do this Git Bash will not work properly, requiring you to remove the Git Bash installation, re-run the installer and to select the "Git from the command line and also from 3rd-party software" option.)
   4. Choosing the SSH executable: select *Use bundled OpenSSH*
   5. Choosing HTTPS transport backend: select *Use the native Windows Secure Channel Library*
   6. Configuring the line ending conversion: select *Checkout Windows-style, commit Unix-style line endings*
   7. Configuring the terminal emulator to use with GitBash: select *Use Windows' default console window*
   8. Choose the default behavior of `git pull`: select *Default (fast-forward or merge)*
   9. Choose a credential helper: select *Git Credential Manager*
   10. Configuring extra options: check the box for *Enable file system caching*
3. Click *Install*
4. Click on *Finish* or *Next*

*** Julia
1. The Julia installer will open the Microsoft Store. Click the "Get" button, then click "Open".
2. Julia will open a console window and begin the installation process.
3. After installing Julia, run the following commands in the Julia console window:
   #+BEGIN_SRC R
   using Pkg
   Pkg.add("IJulia")
   #+END_SRC
4. When the process is complete, you may close Julia

*** R and RStudio
1. Install R, then RStudio
2. Open RStudio. If the workstation has multiple versions of R available, RStudio will ask which one it should use. Select the most recent 64-bit version.
3. A pop-up window will ask if you want to submit crash reports. Click "No"
4. In the RStudio Console window, run the following command:
   #+BEGIN_SRC R
   install.packages("tidyverse")
   #+END_SRC
5. When the process is complete, you may close RStudio

*** uv
Open PowerShell and run the following command:
#+BEGIN_SRC bash
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
#+END_SRC

** Application-specific configuration instructions
After installing, make the following configuration changes.

*** Anaconda Navigator
1. On first startup, Navigator will open a modal window titled "Sign in for AI Coding Help." Select "Do not show again" and close the window.
2. Locate the Anaconda Toolbox block. Click the gear in the upper right corner. If "Remove application" is available as an option (i.e. not grayed out), select it.

*** Chrome
1. Autofill and passwords → Payment methods
   - Disable everything
2. Autofill and passwords → Addresses and more
   - Disable everything
3. Privacy and Security → Ad Privacy
   - Disable everything

*** DB Browser for SQLite
1. 1. Edit → Preferences → General
   - Font size: *10*
2. Edit → Preferences → SQL
   - SQL editor font: *Consolas*
   - SQL editor font size: *12*

*** Firefox
1. Create a folder on the *Desktop* called *Workshop* if it doesn't already exist.
2. General → Tabs
   - Disable "Use AI to suggest tabs and a name for tabs groups"
3. General → Files and Applications → Downloads
   - Select the *Workshop* folder on the Desktop
4. General → Browsing
   - Disable "Recommend extensions as you browse"
   - Disable "Recommend features as you browse"
5. Home
   - Home page and new windows: Select *Custom URLs* and paste https://libguides.ucmerced.edu/software-carpentry into the text box
   - New tabs: *Blank page*
6. Home → Firefox Home Content
   - Disable everything except "Web Search"
7. Search → Search suggestions
   - Disable "Show trending search suggestions"
8. Search → Address bar
   - Disable "Suggestions from Firefox"
   - Disable "Suggestions from sponsors"
9. Privacy & Security → Cookies and Site Data
   - Enable " Delete cookies and site data when Firefox is closed"
10. Privacy & Security → Passwords
    - Disable everything
11. Privacy & Security → Autofill
    - Disable everything
12. Privacy & Security → Firefox Data Collection
    - Disable everything
13. Add the following bookmarks to the Bookmarks Toolbar:
    - Software Carpentry: https://libguides.ucmerced.edu/software-carpentry
    - Box: https://ucmerced.account.box.com/login
    - OneDrive: https://merced-my.sharepoint.com
14. Bookmarks → Show Bookmarks Toolbar

*** Jupyter Lab
1. To run Jupyter Lab, open Anaconda PowerShell Prompt and run the following command:
   #+BEGIN_SRC bash
   jupyter lab
   #+END_SRC
2. Select Firefox as the default browser
3. All Jupyter Lab configuration settings are under Settings → Settings Editor
   1. Code Mirror
      - Enable "Auto Closing Brackets"
      - Font Size: *14*
   2. Notifications
      - Disable "Check for JupyterLab updates"
      - Fetch official Jupyter news: *false*

*** Notepad ++
1. Settings → Style Configurator → Font Style
   - Font name: *Consolas*
   - Font size: *12*
2. Enable "Enable global font"
3. Enable "Enable global font size"

*** PowerToys
1. General → Version & updates
   - Disable everything
2. General → Appearance & behavior
   - Disable "Run at Startup"
3. Input/Output → Keyboard Manager
   - Enable "Keyboard Manager"
   - Click "Remap a key"
   - Click "Add key remapping"
     + Select: *Caps Lock*
     + To Send: *Ctrl (Left)*
   - Click "OK", then click "Continue anyway"

*** RStudio
All RStudio configuration settings are under Tools → Global Options. When you have finished changing the configuration settings, click "Apply" and then click "OK".

1. General
   - Default working directory: *C:/Users/DataVisLabWest*
   - Disable "Restore most recently opened project at startup"
   - Disable "Restore previously opened source documents at startup"
   - Disable "Restore .RData into workspace at startup"
   - Save workspace to .RData on exit: *Never*
   - Disable "Automatically notify me of updates to RStudio"
2. Code → Editing
   - Enable "Insert matching parens"
   - Keybindings: *Emacs*
3. Code → Display
   - Enable "Allow scroll past end of document"
   - Enable "Use rainbow parentheses"
4. Appearance
   - Editor font: *Consolas*
   - Editor font size: *12*
5. Pane layout
   - Set the upper left pane to Console
   - Set the upper right pane to Source

*** COMMENT Git Bash
Superseded? May now inherit from PowerShell profile

Right click → Options
1. Under "Text", click "Select"
   - Under Font, select "Consolas"
   - Under Size, select "12"

*** COMMENT Spyder

* Windows configuration
** Default Folders
1. *Documents/Installers* (copied from model workstation)
2. *Documents/windows-setup* (Derek will clone this from Github)
3. *Desktop/Workshop* (empty folder)

** Desktop
1. Delete all Desktop shortcuts
2. Set background to *Documents/Installers/earth_vir_2016_lrg.jpg* by right-clicking on the file and selecting "Set as desktop background".

** Start Menu
1. Pin the following applications (and unpin all others)
   - Anaconda PowerShell Prompt
   - DB Browser for SQLite
   - Firefox
   - Git Bash
   - Julia
   - MobaXTerm
   - Notepad++
   - RStudio
   - File Explorer
   - Settings

2. Settings → Personalization → Start
   - Disable all settings

** File Explorer
1. Pin *Users/DataVisLabWest* folder to Quick Access. Then navigate to *Users/DataVisLabWest* to configure the settings below.
2. View
   - Select "List"
3. Sort
   - Select "Name"
4. Options → General
   - Disable "Show recently used files"
   - Disable "Show frequently used folders"
   - Disable "Show files from Office.com"
5. Options → View
   - Enable "Show hidden files, folders, and drives"
   - Disable "Hide extensions for known file types"
   - After making changes, click *Apply to folders* button

** Taskbar
1. Remove Windows Store
2. Remove Copilot
3. Remove Edge
4. Add Firefox

** Widgets
1. Settings → Personalization → Taskbar
   - Disable "Widgets"

** Apps
1. Settings → Apps → Default apps → Firefox
   - Next to "Make Firefox your default browser", click *Set default*
2. Settings → Apps → Startup
   - Disable "Microsoft Edge"

** Keyboard
1. Settings → Time & language → Language & region
   1. Next to "English (United States)", click the *...* icon and select *Language Options*
   2. Under "Keyboards", click *Add a keyboard* and select *United States-Dvorak*
2. Settings → Time & language → Typing → Advanced keyboard settings
   1. Select *Input language hot keys*
   2. Select *Between input languages* and click *Change Key Sequence*
   3. Set "Switch Input Language" to *Not Assigned*
   4. Set "Switch Keyboard Layout" to *Not Assigned*
   5. Click *OK*, then click *OK* again

** Search
1. Settings → Privacy & security → Search permissions
   - Under "More settings", disable "Show search highlights"

** Microsoft Edge
*** Page Settings (gear icon on page)
- Disable "Show sponsored links"
- Disable "Show content"
- Disable "Show widgets"
- Disable "Show feed"

*** Settings (in Edge application menu)
1. Profiles
   - Disable "Earn Microsoft Rewards"
2. Privacy, search, and services → Clear browsing data → Choose what to clear every time you close the browser
   - Enable all settings
3. Privacy, search, and services → Privacy
   - Disable all settings
4. Privacy, search, and services → Search and connected experiences
   - Disable all settings except "Use a web service to help resolve navigation errors"
5. Appearance → Copilot and sidebar → Copilot
   - Disable "Show Copilot button on the toolbar"
6. Languages → Writing assistance
   - Disable all settings

** Environment Variables
Create new Environment Variable for the DataVisLabWest user:
R_USER → C:\Users\DataVisLabWest

* COMMENT Reference
This section provides a place to document supporting information and occasional tasks that aren't part of initial configuration.

** RStudio
1. Editor preferences are saved in AppData → Roaming → RStudio → rstudio-prefs.json

** Github authentication with SSH
*** Create a new public key pair
1. Open PowerShell and run the following command:
   #+BEGIN_SRC bash
   # Creates an ed25519 key pair by default
   ssh-keygen -C "your email"
   #+END_SRC
2. Press *Enter* to accept the default key name
3. Enter a password and press *Enter*
4. The new key pair will appear in *Users/DataVisLabWest/.ssh*

*** Add the public key to Github
   1. Log into Github (https://github.com) and navigate to https://github.com/settings/keys
   2. Click *New SSH Key*
   3. Open *Users/DataVisLabWest/.ssh/id_ed25519.pub* using a text editor such as Notepad or Notepad++ ("id_ed25519.pub" is the default name for the public key; if you chose a different name when you created it, the file will be called that instead). Copy the text in the key file and paste it into the "Key" field on Github.
   4. Click *Add SSH key*

** Test suite (in progress)
*** Github authentication with SSH

*** Refresh Git repository
#+BEGIN_SRC bash
cd ~/Documents/windows-setup
git restore .
git pull
#+END_SRC

*** Command line scripts
#+BEGIN_SRC bash
cd ~/windows-setup/scripts
python labtest.py
julia labtest.jl
#+END_SRC

*** Jupyter Lab
1. Start Jupyter Lab
   #+BEGIN_SRC bash
   cd ~/Documents/windows-setup
   jupyter lab
   #+END_SRC
2. Navigate to the ~scripts~ directory.
3. Open and run ~labtest_python.ipynb~
4. Open and run ~labtest_julia.ipynb~

** How to uninstall old Jupyter kernels
#+BEGIN_SRC bash
jupyter kernelspec list
jupyter kernelspec uninstall <kernel-name>
#+END_SRC

** Python virtual environments (uv)

** HPC cluster (MobaXTerm)

* COMMENT How to export this document to other formats
** Export to Github-flavored Markdown using Pandoc
Do this if you want code syntax highlighting and a table of contents on Github.

1. Generate Markdown file
   #+BEGIN_SRC bash
   # Generate markdown file
   pandoc -f org -t gfm --toc --toc-depth=2 --wrap=none -N -s README.org -o README.md

   # Alternatively, generate markdown file with tight spacing for all lists. If a
   # list contains code blocks, Pandoc will automatically format it with wide
   # spacing. The compact_list.lua filter reformats it to remove the whitespace
   # lines.
   pandoc -f org -t gfm --toc --toc-depth=2 --wrap=none -N -s --lua-filter ./compact_list.lua README.org -o README.md

   # Add section headers. This doesn't create clickable links, but it does create
   # section numbers in the document. This is our default.
   pandoc -f org -t gfm --toc --toc-depth=2 --wrap=none -s --lua-filter ./compact_list.lua --lua-filter ./pandoc-section-number-filter.lua README.org -o README.md
   #+END_SRC

2. Delete anything above the Table of Contents, e.g.:
   #+BEGIN_EXAMPLE
   -------------------
     Programming in R
     Derek Devnich
   -------------------
   #+END_EXAMPLE

** Export to Word using Pandoc
#+BEGIN_SRC bash
# pandoc README.org -s -t markdown | pandoc --no-highlight --reference-doc=/Users/gilgamesh/Documents/custom-reference.docx -o docs/KL330_setup.docx

# Spacing is wrong if lua filter runs during markdown creation
pandoc README.org -f org -t gfm -s --wrap=none | pandoc --toc --toc-depth=2 --lua-filter ./compact.lua --no-highlight --reference-doc=/Users/gilgamesh/Documents/Templates/custom-reference-test.docx -o docs/KL330_setup.docx

# Testing markdown creation
pandoc README.org -f org -t gfm -s --wrap=none --toc --toc-depth=2 --lua-filter ./compact.lua -o README.md
# pandoc README.org -f org -t gfm -s --wrap=none | pandoc --no-highlight --reference-doc=/Users/gilgamesh/Documents/Templates/custom-reference-test.docx -o docs/KL330_setup.docx
#+END_SRC

** TODO Implement widow-orphan control for sections and lists
** TODO Find better header styles
